[package]
name = "axum-prod"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = 'src/lib.rs'

# not necessary but better to specify so others can know at a glance
[[bin]]
path = 'src/main.rs'
name = "axum-prod"

[dependencies]
axum = "0.7.1"
reqwest = "0.11.22"
serde = { version = "1.0.193", features = ["derive"] }
sqlx = { version = "0.7.3", default-features = false, features = [
  "macros",
  "postgres",
  "uuid",
  "chrono",
  "migrate",
  "runtime-tokio-rustls",
] }
tokio = { version = "1.34.0", features = ["macros", "rt-multi-thread"] }
