name: Security audit

on:
  # runs on specified intervals
  schedule:
    - cron: "0 0 * * *"
  # runs when there're changes to files that matches pattern
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"

jobs:
  security_audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: taiki-e/install-action@cargo-deny
      - name: Scan for vulnerabilities
        run: cargo deny check advisories
